export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAIL = " FETCH_INGREDIENTS_FAIL";

export const PUTINGREDIENT_START = "PUTINGREDIENT_START";
export const PUTINGREDIENT_SUCCESS = "PUTINGREDIENT_SUCCESS";
export const PUTINGREDIENT_FAIL = "PUTINGREDIENT_FAIL";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START ";
export const FETCH_ORDERS_SUCCESS = " FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = " FETCH_ORDERS_FAIL";
